#!/usr/bin/env node
/**
 * sync-infisical-env — pull ContactLogo's app-level settings from Infisical
 * into a local `.env.local` for dev builds.
 *
 * ContactLogo web is a static Vite SPA: build-time env is inlined by Vite, so
 * the Infisical sole-source-of-truth pattern applies at provisioning time
 * rather than at request time.  This script loads the ContactLogo project's
 * settings set (one environment) and writes the values to `.env.local`
 * (gitignored — `.env.*` is in the root .gitignore), which Vite picks up for
 * `npm run dev` and `npm run build`.  Production builds get their values from
 * the same Infisical project (prod env) synced into the Vercel project
 * environment — see INFISICAL.md.
 *
 * Usage:
 *   INFISICAL_CLIENT_ID=... INFISICAL_CLIENT_SECRET=... \
 *     node --experimental-strip-types scripts/sync-infisical-env.ts
 *
 * Prod is the only environment: `--env` and `INFISICAL_ENV` accept `prod` and
 * nothing else (the dev and staging environments are retired).
 *
 * The machine-identity credentials must come from the operator's secret
 * store — never commit them.  Values are never printed; only key names.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { resolveInfisicalEnvironment } from "./infisical-environment.ts";
import { createInfisicalSettings } from "./infisical-settings.ts";

// Keep in sync with the key inventory in INFISICAL.md.
const PROJECT_ID = "8a0ae9aa-8b67-443e-943d-c55a767dab50";

function quote(value: string): string {
  // .env files: quote when the value contains whitespace or a quote.
  if (/[\s#"'`]/.test(value)) {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

async function main(): Promise<void> {
  const environment = resolveInfisicalEnvironment(process.argv.slice(2));
  const settings = createInfisicalSettings({
    projectId: PROJECT_ID,
    environment,
    refreshIntervalMs: 0, // one-shot sync; no background timer.
  });
  await settings.init();
  try {
    const all = settings.getAll();
    const names = Object.keys(all).sort();
    if (names.length === 0) {
      console.error(
        `[sync-infisical-env] No keys in Infisical project ${PROJECT_ID} environment "${environment}". ` +
          `Add them per INFISICAL.md and re-run.`,
      );
      process.exitCode = 1;
      return;
    }
    // The build reads both plain and VITE_-prefixed names (see vite.config.ts
    // and web/src/engine/settings.ts), so write both forms.
    const lines: string[] = [
      "# Generated by scripts/sync-infisical-env.ts — DO NOT EDIT.",
      `# Infisical project ${PROJECT_ID}, environment "${environment}".`,
      "# Values never printed here; re-run the script to refresh.",
      "",
    ];
    for (const name of names) {
      const value = quote(all[name] ?? "");
      lines.push(`${name}=${value}`);
      if (!name.startsWith("VITE_")) {
        lines.push(`VITE_${name}=${value}`);
      }
    }
    lines.push("");
    const outPath = resolve(import.meta.dirname ?? ".", "..", ".env.local");
    writeFileSync(outPath, lines.join("\n"), { mode: 0o600 });
    console.log(
      `[sync-infisical-env] Wrote ${names.length} settings (${names.join(", ")}) to .env.local from environment "${environment}".`,
    );
  } finally {
    settings.stop();
  }
}

main().catch((error: unknown) => {
  console.error(
    `[sync-infisical-env] Failed: ${error instanceof Error ? error.message : String(error)}`,
  );
  process.exitCode = 1;
});
